//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS28.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TUYEN\\KISS;Initial Catalog=QLNS;Integrated Security=True;Connect Time" +
            "out=15;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;Mul" +
            "tiSubnetFailover=False")]
        public string QLNSConnectionString {
            get {
                return ((string)(this["QLNSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TUYEN\\KISS;Initial Catalog=QLNS;Integrated Security=True;Connect Time" +
            "out=15;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;Mul" +
            "tiSubnetFailover=False")]
        public string QLNSConnectionString1 {
            get {
                return ((string)(this["QLNSConnectionString1"]));
            }
        }
    }
}
